name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test-10:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 10
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - run: npm ci
    - run: npm link
    - run: npm run test-cjs
  test-12:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 12
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - run: npm ci
    - run: npm link
    - run: npm run test-cjs
  test-14:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 14
      uses: actions/setup-node@v1
      with:
        version: 14.x
    - run: npm ci
    - run: npm link
    - run: npm run test-cjs
    - run: npm run test-esm
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: use node 12
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - run: npm ci
    - run: npm run lint
